
napi_value Init(napi_env env, napi_value exports) {
  napi_property_descriptor descriptors[] = {
      {"createWorld", nullptr, CreateWorld, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"destroyWorld", nullptr, DestroyWorld, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"step", nullptr, StepWorld, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setGravity", nullptr, SetGravity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setBodyActivationCallback", nullptr, SetBodyActivationCallback, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setContactCallback", nullptr, SetContactCallback, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"createSphere", nullptr, CreateSphere, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createBox", nullptr, CreateBox, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createCapsule", nullptr, CreateCapsule, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createCylinder", nullptr, CreateCylinder, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createTaperedCapsule", nullptr, CreateTaperedCapsule, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createTaperedCylinder", nullptr, CreateTaperedCylinder, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createConvexHull", nullptr, CreateConvexHull, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createMesh", nullptr, CreateMesh, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createHeightField", nullptr, CreateHeightField, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createStaticCompound", nullptr, CreateStaticCompound, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createMutableCompound", nullptr, CreateMutableCompound, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"addMutableSubShape", nullptr, AddMutableSubShape, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"removeMutableSubShape", nullptr, RemoveMutableSubShape, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"modifyMutableSubShape", nullptr, ModifyMutableSubShape, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"adjustMutableCenterOfMass", nullptr, AdjustMutableCenterOfMass, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"getBodyPosition", nullptr, GetBodyPosition, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getBodyRotation", nullptr, GetBodyRotation, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setBodyPosition", nullptr, SetBodyPosition, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setBodyRotation", nullptr, SetBodyRotation, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getLinearVelocity", nullptr, GetLinearVelocity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setLinearVelocity", nullptr, SetLinearVelocity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getAngularVelocity", nullptr, GetAngularVelocity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setAngularVelocity", nullptr, SetAngularVelocity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"applyImpulse", nullptr, ApplyImpulse, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"addAngularImpulse", nullptr, AddAngularImpulse, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"addForce", nullptr, AddForce, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"addTorque", nullptr, AddTorque, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setFriction", nullptr, SetFrictionValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getFriction", nullptr, GetFrictionValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setRestitution", nullptr, SetRestitutionValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getRestitution", nullptr, GetRestitutionValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setGravityFactor", nullptr, SetGravityFactorValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getGravityFactor", nullptr, GetGravityFactorValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setMotionType", nullptr, SetMotionTypeValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getMotionType", nullptr, GetMotionTypeValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setMotionQuality", nullptr, SetMotionQualityValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getMotionQuality", nullptr, GetMotionQualityValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setObjectLayer", nullptr, SetObjectLayerValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getObjectLayer", nullptr, GetObjectLayerValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setDamping", nullptr, SetDampingValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getDamping", nullptr, GetDampingValue, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"activateBody", nullptr, ActivateBody, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"deactivateBody", nullptr, DeactivateBody, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"removeBody", nullptr, RemoveBody, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"hasBody", nullptr, HasBody, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"isBodyActive", nullptr, IsBodyActive, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setBodySensor", nullptr, SetBodySensor, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"isBodySensor", nullptr, IsBodySensor, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getCenterOfMassPosition", nullptr, GetCenterOfMassPosition, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"rayCastClosest", nullptr, RayCastClosest, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"rayCastAll", nullptr, RayCastAll, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"collideSphereAll", nullptr, CollideSphereAll, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"castSphereAll", nullptr, CastSphereAll, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"castBoxAll", nullptr, CastBoxAll, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"castCapsuleAll", nullptr, CastCapsuleAll, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"queryAABB", nullptr, QueryAABB, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"areBodiesInContact", nullptr, AreBodiesInContact, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"createFixedConstraint", nullptr, CreateFixedConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createDistanceConstraint", nullptr, CreateDistanceConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createHingeConstraint", nullptr, CreateHingeConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createSliderConstraint", nullptr, CreateSliderConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createPointConstraint", nullptr, CreatePointConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createConeConstraint", nullptr, CreateConeConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createSwingTwistConstraint", nullptr, CreateSwingTwistConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createSixDOFConstraint", nullptr, CreateSixDOFConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"removeConstraint", nullptr, RemoveConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setHingeLimits", nullptr, SetHingeLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSliderLimits", nullptr, SetSliderLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setHingeMotor", nullptr, SetHingeMotor, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSliderMotor", nullptr, SetSliderMotor, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setConeHalfAngle", nullptr, SetConeHalfAngle, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSwingTwistLimits", nullptr, SetSwingTwistLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSwingTwistMotor", nullptr, SetSwingTwistMotor, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSixDOFLimits", nullptr, SetSixDOFLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSixDOFMotorState", nullptr, SetSixDOFMotorState, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSixDOFTargetVelocity", nullptr, SetSixDOFTargetVelocity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSixDOFTargetPose", nullptr, SetSixDOFTargetPose, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setHingeMotorSpring", nullptr, SetHingeMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSliderMotorSpring", nullptr, SetSliderMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSwingMotorSpring", nullptr, SetSwingMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setTwistMotorSpring", nullptr, SetTwistMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setSixDOFMotorSpring", nullptr, SetSixDOFMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getHingeMotorSpring", nullptr, GetHingeMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSliderMotorSpring", nullptr, GetSliderMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSwingMotorSpring", nullptr, GetSwingMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getTwistMotorSpring", nullptr, GetTwistMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSixDOFMotorSpring", nullptr, GetSixDOFMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"getHingeAngle", nullptr, GetHingeAngle, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getHingeMotorState", nullptr, GetHingeMotorState, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSliderPosition", nullptr, GetSliderPosition, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSliderMotorState", nullptr, GetSliderMotorState, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSixDOFRotation", nullptr, GetSixDOFRotation, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSixDOFLimits", nullptr, GetSixDOFLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSixDOFMotorState", nullptr, GetSixDOFMotorState, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSwingTwistRotation", nullptr, GetSwingTwistRotation, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSwingTwistMotorState", nullptr, GetSwingTwistMotorState, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getHingeLambdas", nullptr, GetHingeLambdas, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSliderLambdas", nullptr, GetSliderLambdas, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSwingTwistLambdas", nullptr, GetSwingTwistLambdas, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSixDOFLambdas", nullptr, GetSixDOFLambdas, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getConeLambdas", nullptr, GetConeLambdas, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPointLambdas", nullptr, GetPointLambdas, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getFixedLambdas", nullptr, GetFixedLambdas, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getDistanceLambda", nullptr, GetDistanceLambda, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPulleyLambda", nullptr, GetPulleyLambda, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getGearLambda", nullptr, GetGearLambda, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPathLambdas", nullptr, GetPathLambdas, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getHingeLimits", nullptr, GetHingeLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSliderLimits", nullptr, GetSliderLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSwingTwistLimits", nullptr, GetSwingTwistLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createGearConstraint", nullptr, CreateGearConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createPulleyConstraint", nullptr, CreatePulleyConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPulleyLength", nullptr, GetPulleyLength, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setPulleyLength", nullptr, SetPulleyLength, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPulleyLengthLimits", nullptr, GetPulleyLengthLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createPathConstraint", nullptr, CreatePathConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPathFraction", nullptr, GetPathFraction, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPathMaxFraction", nullptr, GetPathMaxFraction, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setPathMotor", nullptr, SetPathMotor, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPathMotorState", nullptr, GetPathMotorState, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setPathMotorSpring", nullptr, SetPathMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPathMotorSpring", nullptr, GetPathMotorSpring, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"setDistanceLimits", nullptr, SetDistanceLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getDistanceLimits", nullptr, GetDistanceLimits, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setDistanceLimitsSpring", nullptr, SetDistanceLimitsSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getDistanceLimitsSpring", nullptr, GetDistanceLimitsSpring, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createRackAndPinionConstraint", nullptr, CreateRackAndPinionConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getRackAndPinionLambda", nullptr, GetRackAndPinionLambda, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"createSkeleton", nullptr, CreateSkeleton, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"addSkeletonJoint", nullptr, AddSkeletonJoint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"finalizeSkeleton", nullptr, FinalizeSkeleton, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSkeletonJointCount", nullptr, GetSkeletonJointCount, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSkeletonJointInfo", nullptr, GetSkeletonJointInfo, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getSkeletonJointIndex", nullptr, GetSkeletonJointIndex, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createRagdollSettings", nullptr, CreateRagdollSettings, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"createRagdoll", nullptr, CreateRagdoll, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"destroyRagdoll", nullptr, DestroyRagdoll, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getRagdollBodyCount", nullptr, GetRagdollBodyCount, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getRagdollBoneBodyId", nullptr, GetRagdollBoneBodyId, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getRagdollBoneTransform", nullptr, GetRagdollBoneTransform, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setRagdollBoneTransform", nullptr, SetRagdollBoneTransform, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setRagdollJointShape", nullptr, SetRagdollJointShape, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setRagdollJointTransform", nullptr, SetRagdollJointTransform, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setRagdollJointConstraint", nullptr, SetRagdollJointConstraint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getRagdollConstraintIds", nullptr, GetRagdollConstraintIds, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"createSkeletonPose", nullptr, CreateSkeletonPose, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"destroySkeletonPose", nullptr, DestroySkeletonPose, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setPoseJoint", nullptr, SetPoseJoint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPoseJoint", nullptr, GetPoseJoint, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setPoseRootOffset", nullptr, SetPoseRootOffset, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPoseRootOffset", nullptr, GetPoseRootOffset, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"calculatePoseJointMatrices", nullptr, CalculatePoseJointMatrices, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getPoseJointCount", nullptr, GetPoseJointCount, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"ragdollSetPose", nullptr, RagdollSetPose, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollGetPose", nullptr, RagdollGetPose, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollDriveToPoseKinematics", nullptr, RagdollDriveToPoseKinematics, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollDriveToPoseMotors", nullptr, RagdollDriveToPoseMotors, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollActivate", nullptr, RagdollActivate, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollIsActive", nullptr, RagdollIsActive, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollGetRootTransform", nullptr, RagdollGetRootTransform, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollGetWorldSpaceBounds", nullptr, RagdollGetWorldSpaceBounds, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollSetGroupID", nullptr, RagdollSetGroupID, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollResetWarmStart", nullptr, RagdollResetWarmStart, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollSetLinearVelocity", nullptr, RagdollSetLinearVelocity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollAddLinearVelocity", nullptr, RagdollAddLinearVelocity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollSetLinearAndAngularVelocity", nullptr, RagdollSetLinearAndAngularVelocity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollAddImpulse", nullptr, RagdollAddImpulse, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollAddToPhysicsSystem", nullptr, RagdollAddToPhysicsSystem, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollRemoveFromPhysicsSystem", nullptr, RagdollRemoveFromPhysicsSystem, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"ragdollStabilize", nullptr, RagdollStabilize, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"snapshotState", nullptr, SnapshotState, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"applySnapshot", nullptr, ApplySnapshot, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"saveScene", nullptr, SaveScene, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"loadScene", nullptr, LoadScene, nullptr, nullptr, nullptr, napi_default, nullptr},

      {"createCharacter", nullptr, CreateCharacter, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"destroyCharacter", nullptr, DestroyCharacter, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"characterUpdate", nullptr, CharacterUpdate, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setCharacterLinearVelocity", nullptr, SetCharacterLinearVelocity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getCharacterLinearVelocity", nullptr, GetCharacterLinearVelocity, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setCharacterPosition", nullptr, SetCharacterPosition, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getCharacterPosition", nullptr, GetCharacterPosition, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"setCharacterRotation", nullptr, SetCharacterRotation, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getCharacterRotation", nullptr, GetCharacterRotation, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getCharacterGroundState", nullptr, GetCharacterGroundState, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getCharacterGroundNormal", nullptr, GetCharacterGroundNormal, nullptr, nullptr, nullptr, napi_default, nullptr},
      {"getCharacterGroundBodyId", nullptr, GetCharacterGroundBodyId, nullptr, nullptr, nullptr, napi_default, nullptr},
#ifdef JPH_DEBUG_RENDERER
      {"getDebugGeometry", nullptr, GetDebugGeometry, nullptr, nullptr, nullptr, napi_default, nullptr},
#endif
  };

  if (napi_define_properties(env, exports, sizeof(descriptors) / sizeof(descriptors[0]), descriptors) != napi_ok) {
    return nullptr;
  }

  // Force Jolt factory cleanup when the NAPI environment tears down (process exit,
  // Worker thread termination). At this point all GC finalizers have already run,
  // but just in case any world was leaked we forcibly reset state so that
  // UnregisterTypes / Factory deletion always happens exactly once.
  napi_add_env_cleanup_hook(env, [](void *) {
    std::lock_guard<std::mutex> guard(gInitMutex);
    if (!gJoltInitialized) return;
    UnregisterTypes();
    delete Factory::sInstance;
    Factory::sInstance = nullptr;
    gJoltInitialized = false;
    gWorldCount.store(0);
  }, nullptr);

  return exports;
}
